language: python

cache: pip

python: 
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - export PYTHONWARNINGS=all
  - python src/manage.py check
  - python src/manage.py test feedback
  - coverage run --omit="*/migrations*" --source="." src/manage.py test feedback

after_success:
  coveralls
