language: python

cache: pip

python: 
  - "3.5"
  - "3.6"
  - "3.7"

env:
    # the Django version from requirements.txt is used
  - $DENV=""
    # the latest Django development version is used
  - $DENV="pip install --upgrade --pre Django"

# allow the Django pre version to fail without failing the entire build
matrix:
  fast_finish: true
  allow_failures:
    - env: $DENV="pip install --upgrade --pre Django"

install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - $DENV
  - pip install coveralls

script:
  - export PYTHONWARNINGS=all
  - python src/manage.py check
  - python src/manage.py test feedback
  - coverage run --omit="*/migrations*" --source="." src/manage.py test feedback

after_success:
  coveralls
